// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: predicato/v1/graph.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node mirrors types.Node (embeddings omitted).
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // NodeType
	GroupId       string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,5,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	EpisodeType   string                 `protobuf:"bytes,7,opt,name=episode_type,json=episodeType,proto3" json:"episode_type,omitempty"` // EpisodeType
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	EntityEdges   []string               `protobuf:"bytes,9,rep,name=entity_edges,json=entityEdges,proto3" json:"entity_edges,omitempty"`
	SourceIds     []string               `protobuf:"bytes,10,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	Level         int32                  `protobuf:"varint,11,opt,name=level,proto3" json:"level,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"` // optional (nil when unset)
	Reference     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=reference,proto3" json:"reference,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,17,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_predicato_v1_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Node) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Node) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Node) GetEpisodeType() string {
	if x != nil {
		return x.EpisodeType
	}
	return ""
}

func (x *Node) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Node) GetEntityEdges() []string {
	if x != nil {
		return x.EntityEdges
	}
	return nil
}

func (x *Node) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *Node) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Node) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Node) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Node) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *Node) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *Node) GetReference() *timestamppb.Timestamp {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *Node) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Edge mirrors types.EntityEdge (BaseEdge fields inlined; embeddings omitted).
type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SourceNodeId  string                 `protobuf:"bytes,3,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"` // BaseEdge.SourceNodeID
	TargetNodeId  string                 `protobuf:"bytes,4,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"` // BaseEdge.TargetNodeID
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Fact          string                 `protobuf:"bytes,6,opt,name=fact,proto3" json:"fact,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`                         // EdgeType
	SourceId      string                 `protobuf:"bytes,8,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // backward-compat alias
	TargetId      string                 `protobuf:"bytes,9,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // backward-compat alias
	Summary       string                 `protobuf:"bytes,10,opt,name=summary,proto3" json:"summary,omitempty"`
	Episodes      []string               `protobuf:"bytes,11,rep,name=episodes,proto3" json:"episodes,omitempty"`
	SourceIds     []string               `protobuf:"bytes,12,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	Strength      float64                `protobuf:"fixed64,13,opt,name=strength,proto3" json:"strength,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	ValidAt       *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=valid_at,json=validAt,proto3" json:"valid_at,omitempty"`
	InvalidAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=invalid_at,json=invalidAt,proto3" json:"invalid_at,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,21,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,22,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_predicato_v1_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Edge) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Edge) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *Edge) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *Edge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Edge) GetFact() string {
	if x != nil {
		return x.Fact
	}
	return ""
}

func (x *Edge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Edge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Edge) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Edge) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Edge) GetEpisodes() []string {
	if x != nil {
		return x.Episodes
	}
	return nil
}

func (x *Edge) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *Edge) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Edge) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Edge) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Edge) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *Edge) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *Edge) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *Edge) GetValidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidAt
	}
	return nil
}

func (x *Edge) GetInvalidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InvalidAt
	}
	return nil
}

func (x *Edge) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Edge) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type NodeSearchConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reranker      string                 `protobuf:"bytes,1,opt,name=reranker,proto3" json:"reranker,omitempty"`
	SearchMethods []string               `protobuf:"bytes,2,rep,name=search_methods,json=searchMethods,proto3" json:"search_methods,omitempty"`
	MinScore      float64                `protobuf:"fixed64,3,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSearchConfig) Reset() {
	*x = NodeSearchConfig{}
	mi := &file_predicato_v1_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSearchConfig) ProtoMessage() {}

func (x *NodeSearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSearchConfig.ProtoReflect.Descriptor instead.
func (*NodeSearchConfig) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{2}
}

func (x *NodeSearchConfig) GetReranker() string {
	if x != nil {
		return x.Reranker
	}
	return ""
}

func (x *NodeSearchConfig) GetSearchMethods() []string {
	if x != nil {
		return x.SearchMethods
	}
	return nil
}

func (x *NodeSearchConfig) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

type EdgeSearchConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reranker      string                 `protobuf:"bytes,1,opt,name=reranker,proto3" json:"reranker,omitempty"`
	SearchMethods []string               `protobuf:"bytes,2,rep,name=search_methods,json=searchMethods,proto3" json:"search_methods,omitempty"`
	MinScore      float64                `protobuf:"fixed64,3,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeSearchConfig) Reset() {
	*x = EdgeSearchConfig{}
	mi := &file_predicato_v1_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeSearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeSearchConfig) ProtoMessage() {}

func (x *EdgeSearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeSearchConfig.ProtoReflect.Descriptor instead.
func (*EdgeSearchConfig) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{3}
}

func (x *EdgeSearchConfig) GetReranker() string {
	if x != nil {
		return x.Reranker
	}
	return ""
}

func (x *EdgeSearchConfig) GetSearchMethods() []string {
	if x != nil {
		return x.SearchMethods
	}
	return nil
}

func (x *EdgeSearchConfig) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_predicato_v1_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{4}
}

func (x *TimeRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type SearchFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *TimeRange             `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	GroupIds      []string               `protobuf:"bytes,2,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	NodeTypes     []string               `protobuf:"bytes,3,rep,name=node_types,json=nodeTypes,proto3" json:"node_types,omitempty"`
	EdgeTypes     []string               `protobuf:"bytes,4,rep,name=edge_types,json=edgeTypes,proto3" json:"edge_types,omitempty"`
	EntityTypes   []string               `protobuf:"bytes,5,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilters) Reset() {
	*x = SearchFilters{}
	mi := &file_predicato_v1_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilters) ProtoMessage() {}

func (x *SearchFilters) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilters.ProtoReflect.Descriptor instead.
func (*SearchFilters) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{5}
}

func (x *SearchFilters) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *SearchFilters) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

func (x *SearchFilters) GetNodeTypes() []string {
	if x != nil {
		return x.NodeTypes
	}
	return nil
}

func (x *SearchFilters) GetEdgeTypes() []string {
	if x != nil {
		return x.EdgeTypes
	}
	return nil
}

func (x *SearchFilters) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

type SearchConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Filters             *SearchFilters         `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	NodeConfig          *NodeSearchConfig      `protobuf:"bytes,2,opt,name=node_config,json=nodeConfig,proto3" json:"node_config,omitempty"`
	EdgeConfig          *EdgeSearchConfig      `protobuf:"bytes,3,opt,name=edge_config,json=edgeConfig,proto3" json:"edge_config,omitempty"`
	ExcludeEntityTypes  []string               `protobuf:"bytes,4,rep,name=exclude_entity_types,json=excludeEntityTypes,proto3" json:"exclude_entity_types,omitempty"`
	PreferredPredicates []string               `protobuf:"bytes,5,rep,name=preferred_predicates,json=preferredPredicates,proto3" json:"preferred_predicates,omitempty"`
	Limit               int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	CenterNodeDistance  int32                  `protobuf:"varint,7,opt,name=center_node_distance,json=centerNodeDistance,proto3" json:"center_node_distance,omitempty"`
	MinScore            float64                `protobuf:"fixed64,8,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	IncludeEdges        bool                   `protobuf:"varint,9,opt,name=include_edges,json=includeEdges,proto3" json:"include_edges,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchConfig) Reset() {
	*x = SearchConfig{}
	mi := &file_predicato_v1_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConfig) ProtoMessage() {}

func (x *SearchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConfig.ProtoReflect.Descriptor instead.
func (*SearchConfig) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{6}
}

func (x *SearchConfig) GetFilters() *SearchFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchConfig) GetNodeConfig() *NodeSearchConfig {
	if x != nil {
		return x.NodeConfig
	}
	return nil
}

func (x *SearchConfig) GetEdgeConfig() *EdgeSearchConfig {
	if x != nil {
		return x.EdgeConfig
	}
	return nil
}

func (x *SearchConfig) GetExcludeEntityTypes() []string {
	if x != nil {
		return x.ExcludeEntityTypes
	}
	return nil
}

func (x *SearchConfig) GetPreferredPredicates() []string {
	if x != nil {
		return x.PreferredPredicates
	}
	return nil
}

func (x *SearchConfig) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchConfig) GetCenterNodeDistance() int32 {
	if x != nil {
		return x.CenterNodeDistance
	}
	return 0
}

func (x *SearchConfig) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *SearchConfig) GetIncludeEdges() bool {
	if x != nil {
		return x.IncludeEdges
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Config        *SearchConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_predicato_v1_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{7}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetConfig() *SearchConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SearchResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResults) Reset() {
	*x = SearchResults{}
	mi := &file_predicato_v1_graph_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResults) ProtoMessage() {}

func (x *SearchResults) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResults.ProtoReflect.Descriptor instead.
func (*SearchResults) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResults) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchResults) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *SearchResults) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *SearchResults) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Episode mirrors types.Episode (ContentEmbedding omitted).
type Episode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	GroupId       string                 `protobuf:"bytes,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Reference     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Episode) Reset() {
	*x = Episode{}
	mi := &file_predicato_v1_graph_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Episode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Episode) ProtoMessage() {}

func (x *Episode) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Episode.ProtoReflect.Descriptor instead.
func (*Episode) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{9}
}

func (x *Episode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Episode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Episode) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Episode) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Episode) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Episode) GetReference() *timestamppb.Timestamp {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *Episode) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Episode) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// AddEpisodeOptions carries the serializable subset of predicato.AddEpisodeOptions
// (GraphModeler / error-handling policy cannot be remoted).
type AddEpisodeOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ExcludedEntityTypes  []string               `protobuf:"bytes,1,rep,name=excluded_entity_types,json=excludedEntityTypes,proto3" json:"excluded_entity_types,omitempty"`
	PreviousEpisodeUuids []string               `protobuf:"bytes,2,rep,name=previous_episode_uuids,json=previousEpisodeUuids,proto3" json:"previous_episode_uuids,omitempty"`
	MaxCharacters        int32                  `protobuf:"varint,3,opt,name=max_characters,json=maxCharacters,proto3" json:"max_characters,omitempty"`
	EntityTypes          *structpb.Struct       `protobuf:"bytes,4,opt,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	EdgeTypes            *structpb.Struct       `protobuf:"bytes,5,opt,name=edge_types,json=edgeTypes,proto3" json:"edge_types,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AddEpisodeOptions) Reset() {
	*x = AddEpisodeOptions{}
	mi := &file_predicato_v1_graph_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEpisodeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEpisodeOptions) ProtoMessage() {}

func (x *AddEpisodeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEpisodeOptions.ProtoReflect.Descriptor instead.
func (*AddEpisodeOptions) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{10}
}

func (x *AddEpisodeOptions) GetExcludedEntityTypes() []string {
	if x != nil {
		return x.ExcludedEntityTypes
	}
	return nil
}

func (x *AddEpisodeOptions) GetPreviousEpisodeUuids() []string {
	if x != nil {
		return x.PreviousEpisodeUuids
	}
	return nil
}

func (x *AddEpisodeOptions) GetMaxCharacters() int32 {
	if x != nil {
		return x.MaxCharacters
	}
	return 0
}

func (x *AddEpisodeOptions) GetEntityTypes() *structpb.Struct {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

func (x *AddEpisodeOptions) GetEdgeTypes() *structpb.Struct {
	if x != nil {
		return x.EdgeTypes
	}
	return nil
}

type AddEpisodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episode       *Episode               `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	Options       *AddEpisodeOptions     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEpisodeRequest) Reset() {
	*x = AddEpisodeRequest{}
	mi := &file_predicato_v1_graph_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEpisodeRequest) ProtoMessage() {}

func (x *AddEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEpisodeRequest.ProtoReflect.Descriptor instead.
func (*AddEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{11}
}

func (x *AddEpisodeRequest) GetEpisode() *Episode {
	if x != nil {
		return x.Episode
	}
	return nil
}

func (x *AddEpisodeRequest) GetOptions() *AddEpisodeOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type AddEpisodeResults struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Episode        *Node                  `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	EpisodicEdges  []*Edge                `protobuf:"bytes,2,rep,name=episodic_edges,json=episodicEdges,proto3" json:"episodic_edges,omitempty"`
	Nodes          []*Node                `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges          []*Edge                `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	Communities    []*Node                `protobuf:"bytes,5,rep,name=communities,proto3" json:"communities,omitempty"`
	CommunityEdges []*Edge                `protobuf:"bytes,6,rep,name=community_edges,json=communityEdges,proto3" json:"community_edges,omitempty"`
	Rules          []*Node                `protobuf:"bytes,7,rep,name=rules,proto3" json:"rules,omitempty"`
	RuleEdges      []*Edge                `protobuf:"bytes,8,rep,name=rule_edges,json=ruleEdges,proto3" json:"rule_edges,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddEpisodeResults) Reset() {
	*x = AddEpisodeResults{}
	mi := &file_predicato_v1_graph_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEpisodeResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEpisodeResults) ProtoMessage() {}

func (x *AddEpisodeResults) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEpisodeResults.ProtoReflect.Descriptor instead.
func (*AddEpisodeResults) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{12}
}

func (x *AddEpisodeResults) GetEpisode() *Node {
	if x != nil {
		return x.Episode
	}
	return nil
}

func (x *AddEpisodeResults) GetEpisodicEdges() []*Edge {
	if x != nil {
		return x.EpisodicEdges
	}
	return nil
}

func (x *AddEpisodeResults) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *AddEpisodeResults) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *AddEpisodeResults) GetCommunities() []*Node {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *AddEpisodeResults) GetCommunityEdges() []*Edge {
	if x != nil {
		return x.CommunityEdges
	}
	return nil
}

func (x *AddEpisodeResults) GetRules() []*Node {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *AddEpisodeResults) GetRuleEdges() []*Edge {
	if x != nil {
		return x.RuleEdges
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_predicato_v1_graph_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{13}
}

func (x *GetNodeRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeRequest) Reset() {
	*x = GetEdgeRequest{}
	mi := &file_predicato_v1_graph_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeRequest) ProtoMessage() {}

func (x *GetEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeRequest.ProtoReflect.Descriptor instead.
func (*GetEdgeRequest) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{14}
}

func (x *GetEdgeRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_predicato_v1_graph_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{15}
}

func (x *StatsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GraphStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeCount      int64                  `protobuf:"varint,1,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	EdgeCount      int64                  `protobuf:"varint,2,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	EpisodeCount   int64                  `protobuf:"varint,3,opt,name=episode_count,json=episodeCount,proto3" json:"episode_count,omitempty"`
	CommunityCount int64                  `protobuf:"varint,4,opt,name=community_count,json=communityCount,proto3" json:"community_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GraphStats) Reset() {
	*x = GraphStats{}
	mi := &file_predicato_v1_graph_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphStats) ProtoMessage() {}

func (x *GraphStats) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphStats.ProtoReflect.Descriptor instead.
func (*GraphStats) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{16}
}

func (x *GraphStats) GetNodeCount() int64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *GraphStats) GetEdgeCount() int64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *GraphStats) GetEpisodeCount() int64 {
	if x != nil {
		return x.EpisodeCount
	}
	return 0
}

func (x *GraphStats) GetCommunityCount() int64 {
	if x != nil {
		return x.CommunityCount
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_predicato_v1_graph_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{17}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_predicato_v1_graph_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_predicato_v1_graph_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_predicato_v1_graph_proto_rawDescGZIP(), []int{18}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_predicato_v1_graph_proto protoreflect.FileDescriptor

const file_predicato_v1_graph_proto_rawDesc = "" +
	"\n" +
	"\x18predicato/v1/graph.proto\x12\fpredicato.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x84\x05\n" +
	"\x04Node\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\x12\x1f\n" +
	"\ventity_type\x18\x05 \x01(\tR\n" +
	"entityType\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12!\n" +
	"\fepisode_type\x18\a \x01(\tR\vepisodeType\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12!\n" +
	"\fentity_edges\x18\t \x03(\tR\ventityEdges\x12\x1d\n" +
	"\n" +
	"source_ids\x18\n" +
	" \x03(\tR\tsourceIds\x12\x14\n" +
	"\x05level\x18\v \x01(\x05R\x05level\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"valid_from\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x128\n" +
	"\treference\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\treference\x123\n" +
	"\bmetadata\x18\x11 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xeb\x06\n" +
	"\x04Edge\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12$\n" +
	"\x0esource_node_id\x18\x03 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x04 \x01(\tR\ftargetNodeId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04fact\x18\x06 \x01(\tR\x04fact\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1b\n" +
	"\tsource_id\x18\b \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\t \x01(\tR\btargetId\x12\x18\n" +
	"\asummary\x18\n" +
	" \x01(\tR\asummary\x12\x1a\n" +
	"\bepisodes\x18\v \x03(\tR\bepisodes\x12\x1d\n" +
	"\n" +
	"source_ids\x18\f \x03(\tR\tsourceIds\x12\x1a\n" +
	"\bstrength\x18\r \x01(\x01R\bstrength\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"valid_from\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x129\n" +
	"\n" +
	"expired_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x125\n" +
	"\bvalid_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\avalidAt\x129\n" +
	"\n" +
	"invalid_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tinvalidAt\x123\n" +
	"\bmetadata\x18\x15 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x127\n" +
	"\n" +
	"attributes\x18\x16 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\"r\n" +
	"\x10NodeSearchConfig\x12\x1a\n" +
	"\breranker\x18\x01 \x01(\tR\breranker\x12%\n" +
	"\x0esearch_methods\x18\x02 \x03(\tR\rsearchMethods\x12\x1b\n" +
	"\tmin_score\x18\x03 \x01(\x01R\bminScore\"r\n" +
	"\x10EdgeSearchConfig\x12\x1a\n" +
	"\breranker\x18\x01 \x01(\tR\breranker\x12%\n" +
	"\x0esearch_methods\x18\x02 \x03(\tR\rsearchMethods\x12\x1b\n" +
	"\tmin_score\x18\x03 \x01(\x01R\bminScore\"k\n" +
	"\tTimeRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xc5\x01\n" +
	"\rSearchFilters\x126\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2\x17.predicato.v1.TimeRangeR\ttimeRange\x12\x1b\n" +
	"\tgroup_ids\x18\x02 \x03(\tR\bgroupIds\x12\x1d\n" +
	"\n" +
	"node_types\x18\x03 \x03(\tR\tnodeTypes\x12\x1d\n" +
	"\n" +
	"edge_types\x18\x04 \x03(\tR\tedgeTypes\x12!\n" +
	"\fentity_types\x18\x05 \x03(\tR\ventityTypes\"\xb6\x03\n" +
	"\fSearchConfig\x125\n" +
	"\afilters\x18\x01 \x01(\v2\x1b.predicato.v1.SearchFiltersR\afilters\x12?\n" +
	"\vnode_config\x18\x02 \x01(\v2\x1e.predicato.v1.NodeSearchConfigR\n" +
	"nodeConfig\x12?\n" +
	"\vedge_config\x18\x03 \x01(\v2\x1e.predicato.v1.EdgeSearchConfigR\n" +
	"edgeConfig\x120\n" +
	"\x14exclude_entity_types\x18\x04 \x03(\tR\x12excludeEntityTypes\x121\n" +
	"\x14preferred_predicates\x18\x05 \x03(\tR\x13preferredPredicates\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x120\n" +
	"\x14center_node_distance\x18\a \x01(\x05R\x12centerNodeDistance\x12\x1b\n" +
	"\tmin_score\x18\b \x01(\x01R\bminScore\x12#\n" +
	"\rinclude_edges\x18\t \x01(\bR\fincludeEdges\"Y\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x122\n" +
	"\x06config\x18\x02 \x01(\v2\x1a.predicato.v1.SearchConfigR\x06config\"\x8f\x01\n" +
	"\rSearchResults\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12(\n" +
	"\x05nodes\x18\x02 \x03(\v2\x12.predicato.v1.NodeR\x05nodes\x12(\n" +
	"\x05edges\x18\x03 \x03(\v2\x12.predicato.v1.EdgeR\x05edges\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"\xa4\x02\n" +
	"\aEpisode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\tR\agroupId\x128\n" +
	"\treference\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\treference\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x98\x02\n" +
	"\x11AddEpisodeOptions\x122\n" +
	"\x15excluded_entity_types\x18\x01 \x03(\tR\x13excludedEntityTypes\x124\n" +
	"\x16previous_episode_uuids\x18\x02 \x03(\tR\x14previousEpisodeUuids\x12%\n" +
	"\x0emax_characters\x18\x03 \x01(\x05R\rmaxCharacters\x12:\n" +
	"\fentity_types\x18\x04 \x01(\v2\x17.google.protobuf.StructR\ventityTypes\x126\n" +
	"\n" +
	"edge_types\x18\x05 \x01(\v2\x17.google.protobuf.StructR\tedgeTypes\"\x7f\n" +
	"\x11AddEpisodeRequest\x12/\n" +
	"\aepisode\x18\x01 \x01(\v2\x15.predicato.v1.EpisodeR\aepisode\x129\n" +
	"\aoptions\x18\x02 \x01(\v2\x1f.predicato.v1.AddEpisodeOptionsR\aoptions\"\xa0\x03\n" +
	"\x11AddEpisodeResults\x12,\n" +
	"\aepisode\x18\x01 \x01(\v2\x12.predicato.v1.NodeR\aepisode\x129\n" +
	"\x0eepisodic_edges\x18\x02 \x03(\v2\x12.predicato.v1.EdgeR\repisodicEdges\x12(\n" +
	"\x05nodes\x18\x03 \x03(\v2\x12.predicato.v1.NodeR\x05nodes\x12(\n" +
	"\x05edges\x18\x04 \x03(\v2\x12.predicato.v1.EdgeR\x05edges\x124\n" +
	"\vcommunities\x18\x05 \x03(\v2\x12.predicato.v1.NodeR\vcommunities\x12;\n" +
	"\x0fcommunity_edges\x18\x06 \x03(\v2\x12.predicato.v1.EdgeR\x0ecommunityEdges\x12(\n" +
	"\x05rules\x18\a \x03(\v2\x12.predicato.v1.NodeR\x05rules\x121\n" +
	"\n" +
	"rule_edges\x18\b \x03(\v2\x12.predicato.v1.EdgeR\truleEdges\"$\n" +
	"\x0eGetNodeRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"$\n" +
	"\x0eGetEdgeRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\")\n" +
	"\fStatsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\x98\x01\n" +
	"\n" +
	"GraphStats\x12\x1d\n" +
	"\n" +
	"node_count\x18\x01 \x01(\x03R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x02 \x01(\x03R\tedgeCount\x12#\n" +
	"\repisode_count\x18\x03 \x01(\x03R\fepisodeCount\x12'\n" +
	"\x0fcommunity_count\x18\x04 \x01(\x03R\x0ecommunityCount\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xa3\x03\n" +
	"\fGraphService\x12B\n" +
	"\x06Search\x12\x1b.predicato.v1.SearchRequest\x1a\x1b.predicato.v1.SearchResults\x12N\n" +
	"\n" +
	"AddEpisode\x12\x1f.predicato.v1.AddEpisodeRequest\x1a\x1f.predicato.v1.AddEpisodeResults\x12;\n" +
	"\aGetNode\x12\x1c.predicato.v1.GetNodeRequest\x1a\x12.predicato.v1.Node\x12;\n" +
	"\aGetEdge\x12\x1c.predicato.v1.GetEdgeRequest\x1a\x12.predicato.v1.Edge\x12@\n" +
	"\bGetStats\x12\x1a.predicato.v1.StatsRequest\x1a\x18.predicato.v1.GraphStats\x12C\n" +
	"\x06Health\x12\x1b.predicato.v1.HealthRequest\x1a\x1c.predicato.v1.HealthResponseB8Z6github.com/soundprediction/predicato/pkg/grpcsvc/pb;pbb\x06proto3"

var (
	file_predicato_v1_graph_proto_rawDescOnce sync.Once
	file_predicato_v1_graph_proto_rawDescData []byte
)

func file_predicato_v1_graph_proto_rawDescGZIP() []byte {
	file_predicato_v1_graph_proto_rawDescOnce.Do(func() {
		file_predicato_v1_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_predicato_v1_graph_proto_rawDesc), len(file_predicato_v1_graph_proto_rawDesc)))
	})
	return file_predicato_v1_graph_proto_rawDescData
}

var file_predicato_v1_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_predicato_v1_graph_proto_goTypes = []any{
	(*Node)(nil),                  // 0: predicato.v1.Node
	(*Edge)(nil),                  // 1: predicato.v1.Edge
	(*NodeSearchConfig)(nil),      // 2: predicato.v1.NodeSearchConfig
	(*EdgeSearchConfig)(nil),      // 3: predicato.v1.EdgeSearchConfig
	(*TimeRange)(nil),             // 4: predicato.v1.TimeRange
	(*SearchFilters)(nil),         // 5: predicato.v1.SearchFilters
	(*SearchConfig)(nil),          // 6: predicato.v1.SearchConfig
	(*SearchRequest)(nil),         // 7: predicato.v1.SearchRequest
	(*SearchResults)(nil),         // 8: predicato.v1.SearchResults
	(*Episode)(nil),               // 9: predicato.v1.Episode
	(*AddEpisodeOptions)(nil),     // 10: predicato.v1.AddEpisodeOptions
	(*AddEpisodeRequest)(nil),     // 11: predicato.v1.AddEpisodeRequest
	(*AddEpisodeResults)(nil),     // 12: predicato.v1.AddEpisodeResults
	(*GetNodeRequest)(nil),        // 13: predicato.v1.GetNodeRequest
	(*GetEdgeRequest)(nil),        // 14: predicato.v1.GetEdgeRequest
	(*StatsRequest)(nil),          // 15: predicato.v1.StatsRequest
	(*GraphStats)(nil),            // 16: predicato.v1.GraphStats
	(*HealthRequest)(nil),         // 17: predicato.v1.HealthRequest
	(*HealthResponse)(nil),        // 18: predicato.v1.HealthResponse
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 20: google.protobuf.Struct
}
var file_predicato_v1_graph_proto_depIdxs = []int32{
	19, // 0: predicato.v1.Node.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: predicato.v1.Node.updated_at:type_name -> google.protobuf.Timestamp
	19, // 2: predicato.v1.Node.valid_from:type_name -> google.protobuf.Timestamp
	19, // 3: predicato.v1.Node.valid_to:type_name -> google.protobuf.Timestamp
	19, // 4: predicato.v1.Node.reference:type_name -> google.protobuf.Timestamp
	20, // 5: predicato.v1.Node.metadata:type_name -> google.protobuf.Struct
	19, // 6: predicato.v1.Edge.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: predicato.v1.Edge.updated_at:type_name -> google.protobuf.Timestamp
	19, // 8: predicato.v1.Edge.valid_from:type_name -> google.protobuf.Timestamp
	19, // 9: predicato.v1.Edge.valid_to:type_name -> google.protobuf.Timestamp
	19, // 10: predicato.v1.Edge.expired_at:type_name -> google.protobuf.Timestamp
	19, // 11: predicato.v1.Edge.valid_at:type_name -> google.protobuf.Timestamp
	19, // 12: predicato.v1.Edge.invalid_at:type_name -> google.protobuf.Timestamp
	20, // 13: predicato.v1.Edge.metadata:type_name -> google.protobuf.Struct
	20, // 14: predicato.v1.Edge.attributes:type_name -> google.protobuf.Struct
	19, // 15: predicato.v1.TimeRange.start:type_name -> google.protobuf.Timestamp
	19, // 16: predicato.v1.TimeRange.end:type_name -> google.protobuf.Timestamp
	4,  // 17: predicato.v1.SearchFilters.time_range:type_name -> predicato.v1.TimeRange
	5,  // 18: predicato.v1.SearchConfig.filters:type_name -> predicato.v1.SearchFilters
	2,  // 19: predicato.v1.SearchConfig.node_config:type_name -> predicato.v1.NodeSearchConfig
	3,  // 20: predicato.v1.SearchConfig.edge_config:type_name -> predicato.v1.EdgeSearchConfig
	6,  // 21: predicato.v1.SearchRequest.config:type_name -> predicato.v1.SearchConfig
	0,  // 22: predicato.v1.SearchResults.nodes:type_name -> predicato.v1.Node
	1,  // 23: predicato.v1.SearchResults.edges:type_name -> predicato.v1.Edge
	19, // 24: predicato.v1.Episode.reference:type_name -> google.protobuf.Timestamp
	19, // 25: predicato.v1.Episode.created_at:type_name -> google.protobuf.Timestamp
	20, // 26: predicato.v1.Episode.metadata:type_name -> google.protobuf.Struct
	20, // 27: predicato.v1.AddEpisodeOptions.entity_types:type_name -> google.protobuf.Struct
	20, // 28: predicato.v1.AddEpisodeOptions.edge_types:type_name -> google.protobuf.Struct
	9,  // 29: predicato.v1.AddEpisodeRequest.episode:type_name -> predicato.v1.Episode
	10, // 30: predicato.v1.AddEpisodeRequest.options:type_name -> predicato.v1.AddEpisodeOptions
	0,  // 31: predicato.v1.AddEpisodeResults.episode:type_name -> predicato.v1.Node
	1,  // 32: predicato.v1.AddEpisodeResults.episodic_edges:type_name -> predicato.v1.Edge
	0,  // 33: predicato.v1.AddEpisodeResults.nodes:type_name -> predicato.v1.Node
	1,  // 34: predicato.v1.AddEpisodeResults.edges:type_name -> predicato.v1.Edge
	0,  // 35: predicato.v1.AddEpisodeResults.communities:type_name -> predicato.v1.Node
	1,  // 36: predicato.v1.AddEpisodeResults.community_edges:type_name -> predicato.v1.Edge
	0,  // 37: predicato.v1.AddEpisodeResults.rules:type_name -> predicato.v1.Node
	1,  // 38: predicato.v1.AddEpisodeResults.rule_edges:type_name -> predicato.v1.Edge
	7,  // 39: predicato.v1.GraphService.Search:input_type -> predicato.v1.SearchRequest
	11, // 40: predicato.v1.GraphService.AddEpisode:input_type -> predicato.v1.AddEpisodeRequest
	13, // 41: predicato.v1.GraphService.GetNode:input_type -> predicato.v1.GetNodeRequest
	14, // 42: predicato.v1.GraphService.GetEdge:input_type -> predicato.v1.GetEdgeRequest
	15, // 43: predicato.v1.GraphService.GetStats:input_type -> predicato.v1.StatsRequest
	17, // 44: predicato.v1.GraphService.Health:input_type -> predicato.v1.HealthRequest
	8,  // 45: predicato.v1.GraphService.Search:output_type -> predicato.v1.SearchResults
	12, // 46: predicato.v1.GraphService.AddEpisode:output_type -> predicato.v1.AddEpisodeResults
	0,  // 47: predicato.v1.GraphService.GetNode:output_type -> predicato.v1.Node
	1,  // 48: predicato.v1.GraphService.GetEdge:output_type -> predicato.v1.Edge
	16, // 49: predicato.v1.GraphService.GetStats:output_type -> predicato.v1.GraphStats
	18, // 50: predicato.v1.GraphService.Health:output_type -> predicato.v1.HealthResponse
	45, // [45:51] is the sub-list for method output_type
	39, // [39:45] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_predicato_v1_graph_proto_init() }
func file_predicato_v1_graph_proto_init() {
	if File_predicato_v1_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_predicato_v1_graph_proto_rawDesc), len(file_predicato_v1_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_predicato_v1_graph_proto_goTypes,
		DependencyIndexes: file_predicato_v1_graph_proto_depIdxs,
		MessageInfos:      file_predicato_v1_graph_proto_msgTypes,
	}.Build()
	File_predicato_v1_graph_proto = out.File
	file_predicato_v1_graph_proto_goTypes = nil
	file_predicato_v1_graph_proto_depIdxs = nil
}
